### ISSUE TITLE
NEEDS MOAR ASSEMBLY

### ISSUE THREAD

**Issue by sdboyer** [tinylib/synapse#21]
after last night's conversation, i am disappoint :broken_heart:

**Comment by philhofer** [comment]
:ok: 

If/when DCCP (or something like it) shows up as a transport option, the checksums and some of the windowing data structures (bitmaps) will probably have assembler attached to them.

[The spinlock lives in this package.](http://github.com/tinylib/spin)

**Comment by sdboyer** [comment]
:clap:
