### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by philhofer** [tinylib/synapse#7]
Logging should probably be more verbose than it is at the moment.

**Comment by ttacon** [comment]
It would definitely be nice, but also to be able to configure the verbosity on the the fly, too. Thoughts on which package (```fmt``` vs ```log``` vs ```glog``` (build in verbosity handling))?

**Comment by philhofer** [comment]
I was thinking just `log`.

One neat thing we can do (in some kind of 'debug' mode) is unpack the entire contents of each request/response as JSON and print it out, along with the request/response ID and name.

**Comment by ttacon** [comment]
Ah, my bad I was thinking of an actual application using synapse. Last question would be, should we have more log levels than just debug (on/off)? I think just having debug is probably fine. What we be a neat way to trigger it though? Just attach another function to a ```Router``` that would allow the user to turn off/on debug logging?

**Comment by philhofer** [comment]
Yeah, having one debug mode is probably enough.

`Router` only sees incoming traffic, but `Handler` sees everything. I think `DebugHandler(synapse.Handler) synapse.Handler` is what we need on the server side. We'll probably need something different on the client side.

**Comment by philhofer** [comment]
See proposal in #19

**Comment by philhofer** [comment]
More-or-less fixed by #19
