### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by philhofer** [tinylib/synapse#9]
Soon? @ttacon

**Comment by philhofer** [comment]
Ok. Moved. But we still need a site.

**Comment by ttacon** [comment]
GitHub pages site or real domain? (Or real domain backed by GitHub pages?)

**Comment by philhofer** [comment]
Real domain backed by ghpages is probably the easiest.

**Comment by ttacon** [comment]
For sure, so maybe we should look for a ghpages template that looks decent for the moment (unless we make a pretty good looking one)?

**Comment by philhofer** [comment]
Yeah, I'm fine with something pre-canned.
